title: Signals and Systems - UFU
author: Universidade Federal de Uberlândia

# Basic execution settings
execute:
  execute_notebooks: off

# Basic HTML settings
html:
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false

# Basic Sphinx settings
sphinx:
  config:
    extensions:
      - myst_nb
      - sphinx_copybutton
      - sphinxcontrib.bibtex
      - jupyter_book
      - sphinx.ext.mathjax

    myst_enable_extensions:
      - colon_fence
      - linkify

    # Bibliography
    bibtex_bibfiles:
      - references.bib

    # Master document
    master_doc: intro
